const abbreviationContents = {
    "1,25D" : "1,25-dihydroxyvitamin D",
    "1-84PTH":	"1-84 parathyroid hormone",
    "24,25D":	"24,25-dihydroxyvitamin D",
    "25D"	:"25-hydroxyvitamin D",
    "25D-DBP":	"25-hydroxyvitamin D–vitamin D binding protein complex",
    "7-84PTH":	"7-84 parathyroid hormone",
    "ACR"	:"albumin–creatinine ratio",
    "AE"	:"adverse event",
    "AEs"	:"adverse events",
    "ALP"	:"alkaline phosphatase",
    "AUC0-t":	"area under the plasma concentration-time curve from time zero to time t",
    "AVD"	:"active vitamin D",
    "ca:cr"	:"calcium–creatinine ratio",
    "ca/cr"	:"calcium–creatinine ratio",
    "caSR"	:"calcium-sensing receptor",
    "CKD"	:"chronic kidney disease",
    "CKD–MBD":	"chronic kidney disease–mineral and bone disorder",
    "Cmax"	:"maximum concentration",
    "CNS"	:"central nervous system",
    "CTX"	:"carboxy-terminal collagen crosslinks",
    "CTXs"	:"carboxy-terminal collagen crosslinks",
    "CTX1"	:"carboxy-terminal collagen crosslinks, type 1",
    "CTX-1"	:"carboxy-terminal collagen crosslinks, type 1",
    "CTx-1"	:"carboxy-terminal collagen crosslinks, type 1",
    "CVD"	:"cardiovascular disease",
    "CYP24A1":	"cytochrome p450 family 24 subfamily A member 1",
    "CYP27B1":	"cytochrome p450 family 27 subfamily B member 1",
    "CYP3A4":	"cytochrome P450 family 3 subfamily A member 4",
    "DBP"	:"vitamin D binding protein",
    "EAP"	:"efficacy assessment period",
    "eGFR"	:"estimated glomerular filtration rate",
    "EoT"	:"end of treatment",
    "ER"	:"extended-release",
    "ERC"	:"extended-release calcifediol",
    "ESRD"	:"end-stage renal disease",
    "FDA"	:"Food and Drug Administration",
    "FGF-23":	"fibroblast growth factor-23",
    "FGF23"	:"fibroblast growth factor23",
    "GFR"	:"glomerular filtration rate",
    "iPTH"	:"intact parathyroid hormone",
    "IR"	:"immediate-release",
    "IRC"	:"immediate-release calcifediol",
    "ITT"	:"intention-to-treat",
    "IV"	:"intravenous",
    "KDIGO"	:"Kidney Disease: Improving Global Outcomes",
    "KDOQI"	:"Kidney Disease Outcome Quality Initiative",
    "MACE"	:"major adverse cardiovascular event",
    "MBD"	:"mineral and bone disorder",
    "MoA"	:"mechanism of action",
    "ND-CKD":	"non-dialysis chronic kidney disease",
    "NVD"	:"nutritional vitamin D",
    "PD"	:"pharmacodynamics",
    "PK"	:"pharmacokinetics",
    "PTH"	:"parathyroid hormone",
    "RCT"	:"randomised controlled trial",
    "RCTs"	:"randomised controlled trials",
    "SE"	:"standard error",
    "sCa"	:"serum calcium",
    "SHPT"	:"secondary hyperparathyroidism",
    "SmPC"	:"summary of product characteristics",
    "sP"	:"serum phosphate",
    "SPC"	:"summary of product characteristics",
    "sPO"	:"serum phosphate",
    "TEAE"	:"treatment-emergent adverse event",
    "TEAEs"	:"treatment-emergent adverse events",
    "VDR"	:"vitamin D receptor",
    "VDRA"	:"vitamin D receptor activator",
    "vs"	:"versus",
    "wPTH"	:"whole parathyroid hormone",
    "BSAP" : "bone-specific alkaline phosphatase",
    "P1NP" : "procollagen 1 amino-terminal propeptide",
    "MACEs"	: "major adverse cardiovascular events",
    "ANOVA" : "Analysis of variance",
    "HR" : "hazard ratio",
    "CI" : "Confidence Interval",
    "RRT": "Renal replacement therapy",
    "FDA":"food and drug administration",
    "ASCO":"American Society of Clinical Oncology",
    "ROI": "return on investment",
    "KPIs": "key performance indicators",
    "KPI": "key performance indicator",
    "RWE": "real world evidence",
    "DME": "diabetic macular edema",
    "FTE": "full-time equivalent",
    "QALY": "Quality-Adjusted Life Year",
    "CHF": "Confoederatio Helvetica Franc [Swiss Franc]",
    "BMD": "Bone Mineral Density",
    "CYP2R1":  "cytochrome P450 family 2 subfamily R member 1"
};
